import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import DashNavBar from "~/components/Player/Dashboard/DashNavBar";
import { Footer, NavBar } from "~/components/common";
import {
  CTAJumbotron,
  FootyFacts,
  GettingStarted,
  RegisterATurf,
  ScheduledGameSessions,
  UpcomingGames,
} from "~/components/landingPage";
import SearchBookPlay from "~/components/landingPage/SearchBookPlay";
import TurfsNearby from "~/components/landingPage/TurfsNearby";


const Home: NextPage = () => {
  const { data: UserData } = useSession();
  // const { data: turfs, refetch: refetchTurfs } = api.turf.getAll.useQuery()

  return (
    <>
      <Head>
        <title>FootyPack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      {UserData?.user ? <DashNavBar /> : <NavBar />}
      
      <UpcomingGames />
      <CTAJumbotron />
      <ScheduledGameSessions />
      <GettingStarted />
      <TurfsNearby />
      <RegisterATurf />
      <FootyFacts />
      <SearchBookPlay />
      <Footer />
    </>
  );
};

export default Home;
