import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Footer, NavBar } from "~/components/common";
import {
  CTAJumbotron,
  FootyFacts,
  GettingStarted,
  RegisterATurf,
  ScheduledGameSessions,
  UpcomingGames,
} from "~/components/landingPage";
import SearchBookPlay from "~/components/landingPage/SearchBookPlay";
import TurfsNearby from "~/components/landingPage/TurfsNearby";
import { Button } from "~/components/ui/button";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <div className="">
      <Head>
        <title>FootyPack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <NavBar className="md:mx-36" />
      <UpcomingGames />
      <CTAJumbotron />
      <ScheduledGameSessions />
      <GettingStarted />
      <TurfsNearby />
      <RegisterATurf />
      <FootyFacts />
      <SearchBookPlay />
      <Footer />
    </div>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );
  console.log("user", sessionData);

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-primary">
        {sessionData && <span>Logged in as {sessionData.user?.firstname}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="bg-bluee-200/10 rounded-full px-10 py-3 font-semibold text-green-500 no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
