import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import React from "react";
import DashNavBar from "~/components/Player/Dashboard/DashNavBar";
import Hero from "~/components/Player/Hero";
import PlayerEvent from "~/components/Player/PlayerEvent";
import PlayerScheduleGame from "~/components/Player/PlayerScheduleGame";
import TurfSect from "~/components/Player/TurfSect";
import { Footer } from "~/components/common";
import { AuthLayout } from "~/components/layouts/ProtectedLayout";
import { getServerAuthSession } from "~/server/auth";


const index = () => {
  return (
    <AuthLayout>
      <Head>
        <title>FootyPack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <div className="bg-slate-50">
        <DashNavBar />
        <Hero />
        <TurfSect />
        <PlayerScheduleGame />
        <PlayerEvent />
        <Footer />
      </div>
    </AuthLayout>
  );
};

export default index;

// export const getServerSideProps = async (
//   context: GetServerSidePropsContext
// ) => {
//   // If the user is already logged in, redirect.
//   // Note: Make sure not to redirect to the same page
//   // To avoid an infinite loop!
//   const session = await getServerAuthSession(context);
//   const { em } = session?.user
//   if (!session) {
//     return { redirect: { destination: "/" } };
//   } else {
//     return {
//       props: {
//         session
//       },
//     };
//   }
// };
